package com.caijing.business.impl;

import java.util.ArrayList;
import java.util.ArrayList;
import com.caijing.business.impl.OrderManagerImpl.*;
import static org.junit.Assert.*;
import org.junit.Test;

import java.util.Calendar;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.caijing.business.OrderManager;
import com.caijing.business.RechargeManager;
import com.caijing.dao.OrderDao;
import com.caijing.dao.ProductDAO;
import com.caijing.dao.RechargeDao;
import com.caijing.dao.UserrightDAO;
import com.caijing.dao.WebUserDao;
import com.caijing.domain.Order;
import com.caijing.domain.OrderPr;
import com.caijing.domain.Product;
import com.caijing.domain.Recharge;
import com.caijing.domain.Userright;
import com.caijing.domain.WebUser;

public class OrderManagerImplTest {

	@Test
	public void type() throws Exception {
		// TODO auto-generated by JUnit Helper.
		assertNotNull(OrderManagerImpl.class);
	}

	@Test
	public void instantiation() throws Exception {
		// TODO auto-generated by JUnit Helper.
		OrderManagerImpl target = new OrderManagerImpl();
		assertNotNull(target);
	}

	@Test
	public void orderByRecharge_A$String$long$long() throws Exception {
		// TODO auto-generated by JUnit Helper.
		OrderManagerImpl target = new OrderManagerImpl();
		String userid = null;
		long rechargeid = 0L;
		long orderid = 0L;
		target.orderByRecharge(userid, rechargeid, orderid);
	}

	@Test
	public void orderByRemain_A$String$long() throws Exception {
		// TODO auto-generated by JUnit Helper.
		OrderManagerImpl target = new OrderManagerImpl();
		String userid = null;
		long orderid = 0L;
		target.orderByRemain(userid, orderid);
	}

	@Test
	public void saveUserright_A$String$long$List() throws Exception {
		// TODO auto-generated by JUnit Helper.
		OrderManagerImpl target = new OrderManagerImpl();
		String userid = null;
		long orderid = 0L;
		List<Integer> products = new ArrayList<Integer>();
		target.saveUserright(userid, orderid, products);
	}

	@Test
	public void saveOrder_A$String$long$List() throws Exception {
		// TODO auto-generated by JUnit Helper.
		OrderManagerImpl target = new OrderManagerImpl();
		String userid = null;
		long orderid = 0L;
		List products = new ArrayList();
		target.saveOrder(userid, orderid, products);
	}

	@Test
	public void getUserrightsByUserid_A$String() throws Exception {
		// TODO auto-generated by JUnit Helper.
		OrderManagerImpl target = new OrderManagerImpl();
		String userid = null;
		List<Userright> actual = target.getUserrightsByUserid(userid);
		List<Userright> expected = null;
		assertEquals(expected, actual);
	}

}
