package com.caijing.domain;

import java.util.Date;

public class OrderPr {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column order_pr.industryid
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	private Integer industryid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column order_pr.orderid
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	private Long orderid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column order_pr.pid
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	private Integer pid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column order_pr.num
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	private Integer num;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column order_pr.cost
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	private Float cost;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column order_pr.ctime
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	private Date ctime;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column order_pr.industryid
	 * @return  the value of order_pr.industryid
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public Integer getIndustryid() {
		return industryid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column order_pr.industryid
	 * @param industryid  the value for order_pr.industryid
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public void setIndustryid(Integer industryid) {
		this.industryid = industryid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column order_pr.orderid
	 * @return  the value of order_pr.orderid
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public Long getOrderid() {
		return orderid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column order_pr.orderid
	 * @param orderid  the value for order_pr.orderid
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public void setOrderid(Long orderid) {
		this.orderid = orderid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column order_pr.pid
	 * @return  the value of order_pr.pid
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public Integer getPid() {
		return pid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column order_pr.pid
	 * @param pid  the value for order_pr.pid
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public void setPid(Integer pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column order_pr.num
	 * @return  the value of order_pr.num
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column order_pr.num
	 * @param num  the value for order_pr.num
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public void setNum(Integer num) {
		this.num = num;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column order_pr.cost
	 * @return  the value of order_pr.cost
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public Float getCost() {
		return cost;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column order_pr.cost
	 * @param cost  the value for order_pr.cost
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public void setCost(Float cost) {
		this.cost = cost;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column order_pr.ctime
	 * @return  the value of order_pr.ctime
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public Date getCtime() {
		return ctime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column order_pr.ctime
	 * @param ctime  the value for order_pr.ctime
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}
}