package com.caijing.domain;

import java.util.Date;

public class Order {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column order.orderid
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	private Long orderid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column order.userid
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	private Long userid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column order.cost
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	private Float cost;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column order.status
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	private Byte status;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column order.ctime
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	private Date ctime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column order.lmodify
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	private Date lmodify;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column order.orderid
	 * @return  the value of order.orderid
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public Long getOrderid() {
		return orderid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column order.orderid
	 * @param orderid  the value for order.orderid
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public void setOrderid(Long orderid) {
		this.orderid = orderid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column order.userid
	 * @return  the value of order.userid
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public Long getUserid() {
		return userid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column order.userid
	 * @param userid  the value for order.userid
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public void setUserid(Long userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column order.cost
	 * @return  the value of order.cost
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public Float getCost() {
		return cost;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column order.cost
	 * @param cost  the value for order.cost
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public void setCost(Float cost) {
		this.cost = cost;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column order.status
	 * @return  the value of order.status
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column order.status
	 * @param status  the value for order.status
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column order.ctime
	 * @return  the value of order.ctime
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public Date getCtime() {
		return ctime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column order.ctime
	 * @param ctime  the value for order.ctime
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column order.lmodify
	 * @return  the value of order.lmodify
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public Date getLmodify() {
		return lmodify;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column order.lmodify
	 * @param lmodify  the value for order.lmodify
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public void setLmodify(Date lmodify) {
		this.lmodify = lmodify;
	}
}