package com.caijing.domain;

public class Product {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column product.pid
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	private Integer pid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column product.name
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	private String name;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column product.isIndustry
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	private Byte isIndustry;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column product.continuedmonth
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	private Integer continuedmonth;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column product.price
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	private Float price;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column product.rightpaths
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	private String rightpaths;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column product.desc
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	private String desc;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product.pid
	 * @return  the value of product.pid
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public Integer getPid() {
		return pid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product.pid
	 * @param pid  the value for product.pid
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public void setPid(Integer pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product.name
	 * @return  the value of product.name
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product.name
	 * @param name  the value for product.name
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product.isIndustry
	 * @return  the value of product.isIndustry
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public Byte getIsIndustry() {
		return isIndustry;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product.isIndustry
	 * @param isIndustry  the value for product.isIndustry
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public void setIsIndustry(Byte isIndustry) {
		this.isIndustry = isIndustry;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product.continuedmonth
	 * @return  the value of product.continuedmonth
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public Integer getContinuedmonth() {
		return continuedmonth;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product.continuedmonth
	 * @param continuedmonth  the value for product.continuedmonth
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public void setContinuedmonth(Integer continuedmonth) {
		this.continuedmonth = continuedmonth;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product.price
	 * @return  the value of product.price
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public Float getPrice() {
		return price;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product.price
	 * @param price  the value for product.price
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public void setPrice(Float price) {
		this.price = price;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product.rightpaths
	 * @return  the value of product.rightpaths
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public String getRightpaths() {
		return rightpaths;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product.rightpaths
	 * @param rightpaths  the value for product.rightpaths
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public void setRightpaths(String rightpaths) {
		this.rightpaths = rightpaths;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product.desc
	 * @return  the value of product.desc
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product.desc
	 * @param desc  the value for product.desc
	 * @ibatorgenerated  Fri Apr 29 09:46:13 CST 2011
	 */
	public void setDesc(String desc) {
		this.desc = desc;
	}
}