package com.caijing.dao.ibatis;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import java.util.List;

import org.junit.BeforeClass;
import org.junit.Test;

import com.caijing.dao.MasterDao;
import com.caijing.domain.Master;
import com.caijing.util.ContextFactory;

public class MasterDaoImplTest {

	static MasterDao target;
	
	@BeforeClass
	public static void setup(){
		target = (MasterDao) ContextFactory.getBean("masterDao");
	}
	
	@Test
	public void type() throws Exception {
		assertNotNull(MasterDaoImpl.class);
	}

	@Test
	public void instantiation() throws Exception {
		assertNotNull(target);
	}

	@Test
	public void getAllMasters_A$Integer$Integer() throws Exception {
		Integer start = 0;
		Integer length = 3;
		List<Master> actual = target.getAllMasters(start, length);
		List<Master> expected = null;
		assertEquals(expected, actual);
	}

	@Test
	public void getMasterByName_A$String() throws Exception {
		// TODO auto-generated by JUnit Helper.
		MasterDaoImpl target = new MasterDaoImpl();
		String name = null;
		Master actual = target.getMasterByName(name);
		Master expected = null;
		assertEquals(expected, actual);
	}

}
