package com.caijing.dao.ibatis;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import java.util.HashMap;
import java.util.Map;

import org.junit.Before;
import org.junit.Test;

import com.caijing.dao.RecommendStockDao;
import com.caijing.domain.RecommendStock;
import com.caijing.util.ContextFactory;

public class RecommendStockDaoImplTest {

	RecommendStockDao dao;

	@Before
	public void setUp() throws Exception {
		dao = (RecommendStockDao) ContextFactory.getBean("recommendStockDao");
	}
	
	@Test
	public void type() throws Exception {
		assertNotNull(RecommendStockDaoImpl.class);
	}

	@Test
	public void instantiation() throws Exception {
		RecommendStockDao target = dao;
		assertNotNull(target);
	}

	@Test
	public void getRecommendStockbyReportid_A$String() throws Exception {
		// TODO auto-generated by JUnit Helper.
		RecommendStockDaoImpl target = new RecommendStockDaoImpl();
		String reportid = null;
		RecommendStock actual = target.getRecommendStockbyReportid(reportid);
		RecommendStock expected = null;
		assertEquals(expected, actual);
	}

	@Test
	public void updateByPrimaryKeySelective_A$Map() throws Exception {
		// TODO auto-generated by JUnit Helper.
		RecommendStockDaoImpl target = new RecommendStockDaoImpl();
		Map<String, Object> parms = new HashMap<String, Object>();
		int actual = target.updateByPrimaryKeySelective(parms);
		int expected = 0;
		assertEquals(expected, actual);
	}

	@Test
	public void selectByReportid_A$String() throws Exception {
		RecommendStockDao target = dao;
		String reportid = "70HAT572";
		RecommendStock actual = target.selectByReportid(reportid);
		RecommendStock expected = null;
		assertEquals(expected, actual);
	}

}
