package com.caijing.dao.ibatis;

import com.caijing.dao.ibatis.UserrightDAOImpl.*;
import static org.junit.Assert.*;
import org.junit.Test;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.caijing.dao.UserrightDAO;
import com.caijing.domain.Userright;
import com.caijing.util.CrudDaoDefault;

public class UserrightDAOImplTest {

	@Test
	public void type() throws Exception {
		// TODO auto-generated by JUnit Helper.
		assertNotNull(UserrightDAOImpl.class);
	}

	@Test
	public void instantiation() throws Exception {
		// TODO auto-generated by JUnit Helper.
		UserrightDAOImpl target = new UserrightDAOImpl();
		assertNotNull(target);
	}

	@Test
	public void getIndustriesByUserid_A$String$String() throws Exception {
		// TODO auto-generated by JUnit Helper.
		UserrightDAOImpl target = new UserrightDAOImpl();
		String uid = null;
		String path = null;
		List<String> actual = target.getIndustriesByUserid(uid, path);
		List<String> expected = null;
		assertEquals(expected, actual);
	}

	@Test
	public void getUserrightByUserid_A$String() throws Exception {
		// TODO auto-generated by JUnit Helper.
		UserrightDAOImpl target = new UserrightDAOImpl();
		String userid = null;
		List<Userright> actual = target.getUserrightByUserid(userid);
		List<Userright> expected = null;
		assertEquals(expected, actual);
	}

	@Test
	public void updateSelective_A$Userright() throws Exception {
		// TODO auto-generated by JUnit Helper.
		UserrightDAOImpl target = new UserrightDAOImpl();
		Userright userright = null;
		boolean actual = target.updateSelective(userright);
		boolean expected = false;
		assertEquals(expected, actual);
	}

}
